# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.box_version = "1905.1"
  config.vm.network "forwarded_port", guest: 1080, host: 8080
  config.vm.network "forwarded_port", guest: 1025, host: 8025
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 1024
  end
  config.vm.provision "shell", path: "script.sh"
end
