---
- name: nginx installation
  hosts: nginx
  vars:
    http_port: 8080
  tasks:
    - name: repo is configured
      template:
        src: ../templates/nginx.repo
        dest: /etc/yum.repos.d/nginx.repo
    - name: nginx is installed
      yum:
        name: nginx
        state: present
      notify:
        - enable nginx
    - name: nginx is configured
      template:
        src: ../templates/nginx.conf
        dest: /etc/nginx/conf.d/default.conf
      notify:
        - restart nginx
  handlers:
    - name: enable nginx
      service:
        name: nginx
        state: started
        enabled: yes
    - name: restart nginx
      service:
        name: nginx
        state: restarted
