# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :inetRouter => {
    :box_name => "centos/7",
    :vm_name => "inetRouter",
    :net => [
      { adapter: 2, virtualbox__intnet: "testBOND" },
      { adapter: 3, virtualbox__intnet: "testBOND" },
      { ip: '192.168.50.10', adapter: 4 }
    ]
  },
  :centralRouter => {
    :box_name => "centos/7",
    :vm_name => "centralRouter",
    :net => [
      { adapter: 2, virtualbox__intnet: "testBOND" },
      { adapter: 3, virtualbox__intnet: "testBOND" },
      { adapter: 4, virtualbox__intnet: "testLAN" },
      { ip: '192.168.50.11', adapter: 5 }
    ]
  },
  :testClient1 => {
    :box_name => "centos/7",
    :vm_name => "testClient1",
    :net => [
      { adapter: 2, virtualbox__intnet: "testLAN" },
      { ip: '192.168.50.12', adapter: 3 }
    ]
  },
  :testClient2 => {
    :box_name => "centos/7",
    :vm_name => "testClient2",
    :net => [
      { adapter: 2, virtualbox__intnet: "testLAN" },
      { ip: '192.168.50.13', adapter: 3 }
    ]
  },
  :testServer1 => {
    :box_name => "centos/7",
    :vm_name => "testServer1",
    :net => [
      { adapter: 2, virtualbox__intnet: "testLAN" },
      { ip: '192.168.50.14', adapter: 3 }
    ]
  },
  :testServer2 => {
    :box_name => "centos/7",
    :vm_name => "testServer2",
    :net => [
      { adapter: 2, virtualbox__intnet: "testLAN" },
      { ip: '192.168.50.15', adapter: 3 }
    ]
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]
      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", ipconf
      end
    end
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbooks/vlan.yml"
    ansible.inventory_path = "provisioning/hosts"
    ansible.host_key_checking = "false"
    ansible.become = "true"
  end
end
