---
- name: configure routers
  hosts: routers
  become: true
  vars_files:
    - ../defaults/main.yml
  tasks:
  - name: install base tools
    apt:
      name:
        - vim
        - traceroute
        - tcpdump
        - net-tools
        - ansible
      update_cache: true
  - name: disable ufw service
    service:
      name: ufw
      state: stopped
      enabled: false
  - name: import frr key
    apt_key:
      url: "https://deb.frrouting.org/frr/keys.asc"
  - name: add frr repo
    apt_repository:
      repo: "deb https://deb.frrouting.org/frr {{ ansible_distribution_release }} frr-stable"
  - name: install frr packages
    apt:
      name:
      - frr
      - frr-pythontools
  - name: set up forward packages across routers
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: "1"
  - name: set up asynchronous routing
    sysctl:
      name: net.ipv4.conf.all.rp_filter
      value: "0"
  - name: base set up ospf
    blockinfile:
      path: /etc/frr/daemons
      block: |
        zebra=yes
        ospfd=yes
  - name: set up ospf
    template:
      src: ../templates/frr.conf.j2
      dest: /etc/frr/frr.conf
      owner: frr
      group: frr
      mode: "0640"
    tags:
      - setup_ospf
  - name: restart frr service
    service:
      name: frr
      state: restarted
      enabled: true
    tags:
      - setup_ospf
