# -*- mode: ruby -*-
# vi: set ft=ruby :

DISK_COUNT=5
DISK_SIZE=100

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = "512"
    vb.customize [ "storagectl", :id, "--name", "SATA", "--add", "sata" ]
    (1..DISK_COUNT).each do |i|
      unless File.exist?("disk#{i}.vdi")
        vb.customize ["createmedium", "disk", "--filename", "disk#{i}.vdi", "--size", DISK_SIZE]
      end
      vb.customize ["storageattach", :id,  "--storagectl", "SATA", "--port", "#{i}", "--device", 0, "--type", "hdd", "--medium", "disk#{i}.vdi"]
    end
  end
  config.vm.provision "shell", env: {"DISK_SIZE" => DISK_SIZE}, inline: <<-SHELL
    yum install mdadm smartmontools hdparm gdisk -y
    export DEVICES=$(lsblk -p | awk -v size=${DISK_SIZE}M '$0 ~ size { printf "%s ", $1 }')
    mdadm --zero-superblock --force ${DEVICES}
    mdadm --create /dev/md0 -l 10 -n 5 ${DEVICES}
    mkdir -p /etc/mdadm
    echo -e "DEVICE partitions\n$(mdadm --detail --scan)" >> /etc/mdadm/mdadm.conf
    parted -s /dev/md0 mklabel gpt \
    mkpart primary ext4 0% 20% \
    mkpart primary ext4 20% 40% \
    mkpart primary ext4 40% 60% \
    mkpart primary ext4 60% 80% \
    mkpart primary ext4 80% 100%
    for i in {1..5}; do \
    mkdir -p /mnt/part$i; \
    mkfs.ext4 /dev/md0p$i; \
    echo "UUID=$(blkid -s UUID -o value /dev/md0p$i) /mnt/part$i ext4 defaults 0 0" >> /etc/fstab; \
    done
    mount -a
    dracut -f
  SHELL
end
