# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :inetRouter => {
    :box_name => "centos/7",
    :vm_name => "inetRouter",
    :net => [
      { ip: '192.168.20.1', adapter: 2, netmask: "255.255.255.252", gateway: '192.168.20.1', virtualbox__intnet: "intnet" },
      { ip: '192.168.50.10', adapter: 3 }
    ]
  },
  :centralRouter => {
    :box_name => "centos/7",
    :vm_name => "centralRouter",
    :net => [
      { ip: '192.168.20.2', adapter: 2, netmask: "255.255.255.252", gateway: '192.168.20.1', virtualbox__intnet: "intnet" },
      { ip: '192.168.50.11', adapter: 3 }
    ]
  },
  :inetRouter2 => {
    :box_name => "centos/7",
    :vm_name => "inetRouter2",
    :net => [
      { adapter: 2, type: "dhcp", name: "vboxnet3" },
      { ip: '192.168.20.3', adapter: 3, netmask: "255.255.255.252", gateway: '192.168.20.1', virtualbox__intnet: "intnet" },
      { ip: '192.168.50.12', adapter: 4 }
    ]
  },
  :centralServer => {
    :box_name => "centos/7",
    :vm_name => "centralServer",
    :net => [
      { ip: '192.168.20.4', adapter: 2, netmask: "255.255.255.252", gateway: '192.168.20.1', virtualbox__intnet: "intnet" },
      { ip: '192.168.50.13', adapter: 3 }
    ]
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]
      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", ipconf
      end
      box.vm.provision "shell",
        run: "always",
        inline: "ip route del default via 10.0.2.2 || true"
    end
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbooks/iptables.yml"
    ansible.inventory_path = "provisioning/hosts"
    ansible.host_key_checking = "false"
    ansible.become = "true"
  end
end
