# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :server => {
    :box_name => "generic/fedora27",
    :vm_name => "ipaserver.otustest.com",
    :net => [
      { ip: '192.168.20.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "ipalan" },
      { ip: '192.168.50.10', adapter: 3 }
    ]
  },
  :client => {
    :box_name => "generic/fedora27",
    :vm_name => "ipaclient.otustest.com",
    :net => [
      { ip: '192.168.20.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "ipalan" },
      { ip: '192.168.50.11', adapter: 3 }
    ]
  }
}

Vagrant.configure(2) do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.hostname = boxconfig[:vm_name]
      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", ipconf
      end
      box.vm.provision "shell",  inline: "sysctl net.ipv6.conf.all.disable_ipv6=0"
      if boxname.to_s == "client"
        box.vm.provision "shell",  inline: "echo '192.168.20.1 ipaserver ipaserver.otustest.com' >> /etc/hosts"
      end
      box.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible-freeipa/playbooks/install-" + boxname.to_s + ".yml"
        ansible.inventory_path = "ansible-freeipa/inventory/hosts.otus"
        ansible.host_key_checking = "false"
        # ansible.verbose = "vvv"
        ansible.become = "true"
      end
    end
  end
end
