# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.box_version = "2004.01"
    config.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.cpus = 1
    end
    config.vm.define "master" do |master|
        master.vm.network "private_network", ip: "192.168.75.10",
        virtualbox__intnet: "net1"
        master.vm.hostname = "master"
        master.vm.provision "shell", inline: <<-SHELL
            yum install -y epel-release
            yum install -y ansible
        SHELL
    end
    config.vm.define "client" do |client|
        client.vm.network "private_network", ip: "192.168.75.11",
        virtualbox__intnet: "net1"
        client.vm.hostname = "client"
        client.vm.provision "shell", inline: <<-SHELL
            sed -i.bak '/PasswordAuthentication/s/no$/yes/' /etc/ssh/sshd_config
            systemctl restart sshd
        SHELL
    end
end
