# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.10.10"
  end
  config.vm.define "client" do |client|
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.10.20"
  end
  config.vm.define "ras" do |ras|
    ras.vm.hostname = "ras"
    ras.vm.network "private_network", ip: "192.168.10.30"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbooks/openvpn.yml"
    ansible.become = "true"
    ansible.limit = "all"
  end
end
